# Generated by Django 5.2.6 on 2025-09-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_price_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
