# Generated by Django 5.2.6 on 2025-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customer_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
