# Generated by Django 5.2.6 on 2025-09-19 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_brand_webhook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='webhook_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
