# Generated by Django 5.2.6 on 2025-09-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_forwarded_to_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='confirmed_at',
            new_name='responded_at',
        ),
    ]
