# Generated by Django 5.2.6 on 2025-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='delivery_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='delivery_company',
            field=models.CharField(blank=True, choices=[('bosta', 'Bosta')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
