# Generated by Django 5.2.6 on 2025-10-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_brand_delivery_api_key_brand_delivery_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BostaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosta_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='EG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BostaDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosta_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='orders.bostacity')),
            ],
        ),
    ]
