# Generated by Django 5.2.6 on 2025-10-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_seed_bosta_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='district',
        ),
        migrations.AddField(
            model_name='customer',
            name='bosta_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bostacity'),
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('bosta_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bostacity')),
                ('bosta_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bostadistrict')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='orders.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='default_pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.pickuplocation'),
        ),
    ]
