# Generated by Django 5.2.7 on 2025-10-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_state_customer_district_customer_bosta_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The product name from Shopify/WooCommerce', max_length=255)),
                ('variant', models.CharField(blank=True, help_text="The variant name, e.g., 'S', 'Red', 'Large'", max_length=255, null=True)),
                ('bosta_id', models.CharField(blank=True, help_text="The unique _id from Bosta's List Products API", max_length=100, null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.brand')),
            ],
        ),
    ]
