# Generated by Django 5.2.7 on 2025-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bostadistrict',
            name='bosta_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
