# Generated by Django 5.2.7 on 2025-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_bostadistrict_bosta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bostadistrict',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
