# Generated by Django 5.2.8 on 2025-11-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_bostadistrict_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='delivery_company',
            field=models.CharField(blank=True, choices=[('bosta', 'Bosta'), ('aramex', 'Aramex')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AramexConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Aramex Account Username (Email)', max_length=255)),
                ('password', models.CharField(help_text='Aramex Account Password', max_length=255)),
                ('account_number', models.CharField(help_text='Aramex Account Number', max_length=50)),
                ('account_pin', models.CharField(help_text='Aramex Account PIN', max_length=50)),
                ('account_entity', models.CharField(help_text='Aramex Account Entity (e.g., CAI)', max_length=10)),
                ('account_country_code', models.CharField(default='EG', help_text='Aramex Account Country Code', max_length=10)),
                ('version', models.CharField(default='v1.0', help_text='API Version', max_length=10)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aramex_configuration', to='orders.brand')),
            ],
        ),
    ]
