# Generated by Django 5.2.8 on 2025-12-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_aramexcity_aramexdistrict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='delivery_company',
            field=models.CharField(blank=True, choices=[('bosta', 'Bosta'), ('aramex', 'Aramex'), ('khazenly', 'Khazenly'), ('other', 'Other / Not Listed')], max_length=50, null=True),
        ),
    ]
