# Generated by Django 5.2.8 on 2025-12-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_brand_user_alter_brand_delivery_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
