# Generated by Django 5.2.8 on 2025-12-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderitem_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhazenlyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Consumer Key', max_length=255)),
                ('client_secret', models.CharField(help_text='Consumer Secret', max_length=255)),
                ('store_url', models.CharField(help_text='e.g. FASHONSTA.com', max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Paste the Refresh Token you got from the handshake here.', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False, help_text='Checked = Production, Unchecked = Testing')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khazenly_configuration', to='orders.brand')),
            ],
        ),
    ]
