# Generated by Django 5.2.8 on 2025-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_khazenlyconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhazenlyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="The exact city name required by Khazenly API (e.g., 'Cairo', 'Giza', 'Mahalla')", max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Khazenly Cities',
            },
        ),
    ]
